class AppConstants:
    CTG_BILLING = 'Billing'
    CTG_TECHNICAL_SUPPORT = 'Technical Support'
    CTG_PRODUCT_INQUIRY = 'Product Inquiry'
    CTG_COMPLAINT = 'Complaint'
    CTG_COMPLIMENT = 'Compliment'
    CLASSIFICATION_CATEGORIES = [
        CTG_BILLING,
        CTG_TECHNICAL_SUPPORT,
        CTG_PRODUCT_INQUIRY,
        CTG_COMPLAINT,
        CTG_COMPLIMENT,
    ]


class WfResponses:
    SUCCESS = 100
    FAILURE = 101
    PARTIAL_SUCCESS = 102
    NO_ACTION_NEEDED = 103
    TIMEOUT = 104
    INVALID_INPUT = 105
    UNAUTHORIZED = 106
    NOT_FOUND = 107
    CONFLICT = 108
    SERVER_ERROR = 109
    SERVICE_UNAVAILABLE = 110
    DO_NOT_PROCEED_FURTHER = 111
    PROCEED_TO_NEXT_STEP = 112
    RETRY_CURRENT_STEP = 113
    ABORT_WORKFLOW = 114
    COMPLETE_WORKFLOW = 115


class TrainingConstants:
    DEFAULT_TRAINING_PIPELINE_NAME = "CustomerSupportFineTuningTrainingPipeline"
    KEY_TRAINING_PIPELINE_NAME = "TRAINING_PIPELINE_NAME"
